### PR TITLE
[Android] Use the Java 8 Date/Time API.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
* Enable [Java 8 API desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).
* Increase the minimum API level to 4 (the minimum supported by multidex).
* Use the Java 8 Date/Time API in `Utils`.

### CODE REVIEW

**Comment by virxkane** [comment]
All the same, tell me, why are you doing this, why are you promoting Java 8 features? You say the code will be simpler, a controversial statement, but okay.
Do you want to make any changes to this project (except for Java 8 features) and for this you bring the source code into a form that suits you?
Or just translate codebase to Java 8? What for?

**Comment by virxkane** [comment]
I hope you are testing all the replaced code? On all supported versions of Android? Then we don't have to answer the questions, why is my favorite program not working anymore?

**Comment by Isira-Seneviratne** [comment]
> All the same, tell me, why are you doing this, why are you promoting Java 8 features? You say the code will be simpler, a controversial statement, but okay.
> Do you want to make any changes to this project (except for Java 8 features) and for this you bring the source code into a form that suits you?
> Or just translate codebase to Java 8? What for?
> 
> 

I thought the new features would be helpful, and they aren't restricted by API level anymore: https://jakewharton.com/androids-java-8-support/

**Comment by virxkane** [comment]
So you translate the sources to Java 8 for some abstract good?

**Comment by Isira-Seneviratne** [comment]
> So you translate the sources to Java 8 for some abstract good?

Yeah, it doesn't affect the functionality.

**Comment by Isira-Seneviratne** [comment]
> > So you translate the sources to Java 8 for some abstract good?
> 
> Yeah, the new language features don't affect the functionality.

**Comment by virxkane** [comment]
> Yeah, it doesn't affect the functionality.

Can you test your changes on Android 4.0, Android 2.3? Yes, of course, it seems like it should work, but have you tested?

**Comment by virxkane** [comment]
Will there be no performance losses?
In addition to the fact that Java 8 features should work on older versions of Android, you could accidentally make bugs when translating to Java 8, which affected most of the code, so this cannot without extensive testing.
That is why I ask, did you test at least the main functionality of the program?

**Comment by Isira-Seneviratne** [comment]
Yeah, I ran the app and didn't encounter any issues.

**Comment by Isira-Seneviratne** [comment]
> Will there be no performance losses?
> In addition to the fact that Java 8 features should work on older versions of Android, you could accidentally make bugs when translating to Java 8, which affected most of the code, so this cannot without extensive testing.
> That is why I ask, did you test at least the main functionality of the program?

I made the changes with the help of Android Studio. It automatically converted interface declarations to lambdas.

**Comment by virxkane** [comment]
> Yeah, I ran the app and didn't encounter any issues.

Android 2.2, 2.3, 4.0.4, 4.2, etc ???

**Comment by Isira-Seneviratne** [comment]
> > Yeah, I ran the app and didn't encounter any issues.
> 
> Android 2.2, 2.3, 4.0.4, 4.2, etc ???

Testing the language features on all API levels isn't necessary, because Gradle converts the code to run on all API levels: https://jakewharton.com/androids-java-8-support/#source-transformation

**Comment by virxkane** [comment]
Yes, of course, but is there any disadvantages in this desugaring, for example, slowing down?

**Comment by Isira-Seneviratne** [comment]
I didn't encounter any performance issues or anything like that.

**Comment by Isira-Seneviratne** [comment]
I encountered issues with using an AVD running Android Donut, but it seems the solution is to install an older version of the Android SDK: https://stackoverflow.com/questions/60187172/emulate-android-1-6-donut-with-arm-abi

If this PR works, I'll reopen it.

**Comment by Isira-Seneviratne** [comment]
Unfortunately, I couldn't get the emulator to run Android versions older than ICS.

**Pull request closed without merging**
