### PR TITLE
Fixes for version 3.2.47.

### PR DESCRIPTION
**Pull request by virxkane**
1. org.coolreader.CoolReader.loadDocumentFromUri(): changed catch level from FileNotFoundException to common Exception to catch also SecurityException and may be something yet.
2. Google Drive synchronization improvements:
* Changes (currently reading book, reading position) in ReaderView updated upon user request.
* Synchonization progressbar less intrusive.
* Synchonization progressbar disabled for 'Sync To' operations unless it launched by the user manually from menu item in the reading menu.
* Periodic autolaunch the 'Sync To' operations to save changes to the cloud.
3. SEGFAULT fixed.
    Stacktrace:
```
    #00  pc 000000000010727c updateStyleDataRecursive(ldomNode*, LVDocViewCallback*, int&) at coolreader/crengine/src/lvtinydom.cpp:16700
    #01  pc 000000000010728c updateStyleDataRecursive(ldomNode*, LVDocViewCallback*, int&) at coolreader/crengine/src/lvtinydom.cpp:16701
    #02  pc 000000000010728c updateStyleDataRecursive(ldomNode*, LVDocViewCallback*, int&) at coolreader/crengine/src/lvtinydom.cpp:16701
    #03  pc 000000000010728c updateStyleDataRecursive(ldomNode*, LVDocViewCallback*, int&) at coolreader/crengine/src/lvtinydom.cpp:16701
    #04  pc 000000000010728c updateStyleDataRecursive(ldomNode*, LVDocViewCallback*, int&) at coolreader/crengine/src/lvtinydom.cpp:16701
    #05  pc 000000000010728c updateStyleDataRecursive(ldomNode*, LVDocViewCallback*, int&) at coolreader/crengine/src/lvtinydom.cpp:16701
    #06  pc 0000000000104c30 initNodeStyleRecursive at coolreader/crengine/src/lvtinydom.cpp:16714
    #07  pc 0000000000232ec8 LVDocView::Render(int, int, LVRendPageList*) at coolreader/crengine/src/lvdocview.cpp:2821
    #08  pc 0000000000232bb8 LVDocView::checkRender() at coolreader/crengine/src/lvdocview.cpp:593
    #09  pc 0000000000235404 LVDocView::checkPos() at coolreader/crengine/src/lvdocview.cpp:603
    #10  pc 00000000000c4fac Java_org_coolreader_crengine_DocView_getPositionPropsInternal at coolreader/android/jni/docview.cpp:1698
```
4. Patch from @pkb about odt support: allow image processing inside text-box (image with caption).
5. Try to fix NPE:
```
    java.lang.NullPointerException:
      at org.coolreader.CoolReader.lambda$updateGoogleDriveSynchronizer$3$CoolReader (CoolReader.java:2)                    // CoolReader.java: 423-426
      at org.coolreader.-$$Lambda$CoolReader$tQK7aReMomT22Zh2hsG9N9tzRxk.run (Unknown Source:2)                                             // CoolReader.java:
      at org.coolreader.crengine.BaseActivity.lambda$askConfirmation$8 (BaseActivity.java:1)
      at org.coolreader.crengine.-$$Lambda$BaseActivity$jzEQkbXz4Ip6d9_0uhqhKmE7TZ0.onClick (Unknown Source:2)              // CoolReader.java: 418
      at com.android.internal.app.AlertController$ButtonHandler.handleMessage (AlertController.java:172)
      at android.os.Handler.dispatchMessage (Handler.java:106)
```
6. The situation when the synchronization operation required re-authorization on Google Drive has been taken into account.

### CODE REVIEW

**Comment by poire-z** [comment]
@virxkane : about `3 SEGFAULT fixed.`, any more info about the document on which this happened ?
Because it looks like it shouldn't happen.
```c
    int n = node->getChildCount();
    for ( int i=0; i<n; i++ ) {
        ldomNode * child = node->getChildNode(i);
        if ( child->isElement() )
```
There shouldn't be any NULL child if we iterate between 0 and getChildCount() excluded...
If we do get one, there is something really messed up elsewhere in the children management :/

**Comment by virxkane** [comment]
@poire-z Sorry, I have only stack trace.

**Comment by poire-z** [comment]
I looked at your #167 - but no idea. But it looks like toStringV1() would iterate the same way a node's children (but like many other stuff do).
(I guess we can't know if these 2 stack traces are from the same user ? :)

**Comment by virxkane** [comment]
Yes, only stack trace :(

**Pull request merged**
