### PR TITLE
HarfBuzz kerning optimization - added cache for character's interspac…

### PR DESCRIPTION
**Pull request by virxkane**
HarfBuzz kerning optimization - added cache for character's interspace and width, that significaly impove performance.
But with such optimization impossible to draw ligatures, then added new option "Use ligatures" in settings dialog (disabled by default).
When this option enabled performed full slowly harfBuzz shaping.
Tested desktop version (GUI=QT5, Linux, Windows) and android version.

Edit: this PR fix issue #37.

### CODE REVIEW

**Comment by poire-z** [comment]
Reporting some stuff noticed while integrating this into KOReader:

Your hash implementation for triplets seems not robust:
With a string `aaaaaabaaaaa`:
```c
    lUInt32 orighash = getHash((lUInt32)triplet.Char) ^ getHash((lUInt32)triplet.prevChar) ^ getHash((lUInt32)triplet.nextChar);
    lUInt32 hash = (((
           getHash((lUInt32)triplet.Char) )*31
         + getHash((lUInt32)triplet.prevChar) )*31
         + getHash((lUInt32)triplet.nextChar) );
    // Or possibly  less expensive:
    lUInt32 newhash = getHash( (lUInt64)triplet.Char + (((lUInt64)triplet.prevChar)<<16) + (((lUInt64)triplet.nextChar)<<32) );
    printf("orighash: %x hash1: %x hash2: %x\n", orighash, hash, newhash);
```
gives:
```
orighash: 282a9 hash1: f4590033 hash2: b6e3a5d
orighash: 282a9 hash1: f4590033 hash2: b6e3a5d
orighash: b6e2e9e hash1: 5662d2de hash2: b7633a5d aaa
orighash: b6e2e9e hash1: 5662d2de hash2: b7633a5d aaa
orighash: b6e2e9e hash1: 5662d2de hash2: b7633a5d aaa
orighash: b6e2e9e hash1: 5662d2de hash2: b7633a5d aaa
orighash: b8c52b3 hash1: 5680f6f3 hash2: b7633a7c aab  (same orighash)
orighash: b8c52b3 hash1: c78845b3 hash2: b7815e72 aba  (same orighash)
orighash: b8c52b3 hash1: 5a093169 hash2: db783a5d baa  (same orighash)
orighash: b6e2e9e hash1: 5662d2de hash2: b7633a5d aaa
orighash: b6e2e9e hash1: 5662d2de hash2: b7633a5d aaa
orighash: b6e2e9e hash1: 5662d2de hash2: b7633a5d aaa
orighash: 3c70549 hash1: 4ebba989 hash2: b763327e
orighash: 8aba97e hash1: 9074fed4 hash2: afbc0549
```

Your `_hb_features` has now 2 elements, so the call to hb_shape should be:
```
- hb_shape(_hb_font, _hb_buffer, _hb_features, 1);
+ hb_shape(_hb_font, _hb_buffer, _hb_features, 2);
```
(although it seems to work with 1, ligatures are there...)

Also, a question:
In both the harfbuzz code (with or without ligatures), you/we use something like this for the x position for drawing:
`buf->Draw(x + item->origin_x + posInfo.offset,`

Wondering if `item->origin_x` and `posInfo.offset` (=`glyph_pos[cluster].x_offset`) must really be added, or are the same thing (the former from Freetype, the later from Harfbuzz)

But I seem to always get with latin text `x_offset=0` and occasionally `origin_x=1` or `origin_x=2`.
With some text with arabic words (that I can't read nor appreciate the rendering) it seems we get `x_offset=1` and `origin_x=1` thus...:
```
posInfo.offset=1 , item->origin_x=1
posInfo.offset=1 , item->origin_x=1
posInfo.offset=-1 , item->origin_x=-1
posInfo.offset=1 , item->origin_x=1
posInfo.offset=1 , item->origin_x=1
posInfo.offset=1 , item->origin_x=1
posInfo.offset=1 , item->origin_x=1
```

Might be that harfbuzz' `x_offset=0` should really replace and cancel FreeType's `origin_x=1` ?
Couldn't find a doc or some sample code that would give me a definitive answer :|

**Comment by virxkane** [comment]
Although no, item->origin_x is necessary. It depends on kerning table in font. For example, urw-fonts, "URW Gothic L Book Oblique" ( http://vntex.sourceforge.net/, or in attach [a010033l.zip](https://github.com/buggins/coolreader/files/2753271/a010033l.zip) ) Without item->origin_x it looks ugly.

**Comment by poire-z** [comment]
> Ok, I agree with you, but which hash implementation is best for you opinion, hash1 or hash2?

I'll go with hash2, looks faster.

> I can't find this line nor in this PR nor in master. Merge conflict problems?

Indeed ! My bad, I forgot to change the 1 into a 2 while updating the variable name (I did merge manually). You had it right :)

> Although no, item->origin_x is necessary

OK, just did some test and I agree: the current `item->origin_x + posInfo.offset` is best.
For comparisons (zoomed out in a web browser and comparing with Ctrl-Tab):
With Bitter font : [Current origin+offset ](https://user-images.githubusercontent.com/24273478/51088207-0d0f1380-175d-11e9-9a57-09cb851edaf0.png) vs [Harfbuzz offset only:](https://user-images.githubusercontent.com/24273478/51088206-0aacb980-175d-11e9-88d0-c69383969dc8.png)
With FreeSerif : [Current origin+offset](https://user-images.githubusercontent.com/24273478/51088280-f2896a00-175d-11e9-894b-ad2484e0daed.png) vs [Harfbuzz offset only](https://user-images.githubusercontent.com/24273478/51088282-f4532d80-175d-11e9-9094-77e5a6c0bf81.png)

**Comment by virxkane** [comment]
@poire-z You can use my test program to quickly test some features of text rendering.
https://github.com/virxkane/freetype_textdraw

**Pull request merged**
